name: Super-Linter

on: push

jobs:
  super-on:
    name: Lint code base
    runs-on:
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
