name: Super-Linter

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
      - name: Build
        run: dotnet build
      - name: Run tests
        run: dotnet test
